## Task 10.1

## Part 1 - solve with numpy functions

In [27]:
import numpy as np
import time

start_time = time.time()
A = np.array([[4, 1, -2, 9], [1, -3, 4, -7], [3, -2, 4, -12], [1, 2, 4, -12]])
b = np.array([-9, 7, 12, 12])

numpy_solution = np.linalg.solve(A, b)

print(numpy_solution)
print(time.time() - start_time)

[ 1.67767035e-16 -9.32587341e-16 -1.12996032e-15 -1.00000000e+00]
0.0021729469299316406


## Part 2 - solve with Gaussian elimination


In [30]:
start_time = time.time()
A = [[4, 1, -2, 9], [1, -3, 4, -7], [3, -2, 4, -12], [1, 2, 4, -12]]
b = [-9, 7, 12, 12]

n = len(A)

# Convert to augmented matrix
for i in range(n):
    A[i].append(b[i])

# Gaussian elimination
for i in range(n):
    # Pivot for column
    max_row = max(range(i, n), key=lambda r: abs(A[r][i]))
    A[i], A[max_row] = A[max_row], A[i]

    # Make diagonal element 1
    pivot = A[i][i]
    for j in range(i, n + 1):
        A[i][j] /= pivot

    # Eliminate column
    for k in range(i + 1, n):
        factor = A[k][i]
        for j in range(i, n + 1):
            A[k][j] -= factor * A[i][j]

# Back substitution
x = [0] * n
for i in range(n - 1, -1, -1):
    x[i] = A[i][-1] - sum(A[i][j] * x[j] for j in range(i + 1, n))

    
print(x)
print(time.time() - start_time)

[0.0, 0.0, 0.0, -1.0]
0.0011019706726074219


## Part 3 - solve with Cramer's rule

In [31]:
start_time = time.time()
def determinant(matrix):
    # Base case: if matrix is 2x2
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    # Recursive case: expansion by the first row
    det = 0
    for c in range(len(matrix)):
        minor = [row[:c] + row[c + 1:] for row in matrix[1:]]
        det += ((-1) ** c) * matrix[0][c] * determinant(minor)
    return det

original_matrix = [[4, 1, -2, 9], [1, -3, 4, -7], [3, -2, 4, -12], [1, 2, 4, -12]]
rhs_vector = [-9, 7, 12, 12]

det_original = determinant(original_matrix)

if det_original == 0:
    raise ValueError("The system does not have a unique solution.")

# Cramer's rule
solutions = []
for i in range(4):
    modified_matrix = [row[:i] + [rhs_vector[j]] + row[i + 1:] for j, row in enumerate(original_matrix)]
    solutions.append(determinant(modified_matrix) / det_original)

print(solutions)
print(time.time() - start_time)

[-0.0, -0.0, -0.0, -1.0]
0.001300811767578125


## Part 4 - compare solutions with numpy.allclose()

In [19]:
comparison_result_1 = np.allclose(numpy_solution, x)
comparison_result_2 = np.allclose(numpy_solution, solutions)
comparison_result_3 = np.allclose(solutions, x)
print(comparison_result_1)
print(comparison_result_2)
print(comparison_result_3)

True
True
True


## Task 10.2

## Part 1 - calculate matrix with numpy

In [32]:
start_time = time.time()
A = np.array([[7, 2, 0], [-7, -2, 1], [1, 1, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 1]])

A_squared = np.matmul(A, A)
B_squared = np.matmul(B, B)

difference = A_squared - B_squared
sum_ab = A + B

numpy_result = np.matmul(difference, sum_ab)
print(numpy_result)
print(time.time() - start_time)

[[ 138   88   68]
 [-154 -100  -78]
 [ -14  -16  -12]]
0.001528024673461914


## Part 2 - calculate without numpy

In [34]:
start_time = time.time()
A = [[7, 2, 0], [-7, -2, 1], [1, 1, 0]]
B = [[0, 2, 3], [1, 0, -2], [3, 1, 1]]

def matrix_multiply(X, Y):
    result = [[sum(a * b for a, b in zip(X_row, Y_col)) for Y_col in zip(*Y)] for X_row in X]
    return result

def matrix_add(X, Y):
    return [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

def matrix_subtract(X, Y):
    return [[X[i][j] - Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]

A_squared = matrix_multiply(A, A)
B_squared = matrix_multiply(B, B)

difference = matrix_subtract(A_squared, B_squared)
sum_ab = matrix_add(A, B)

result = matrix_multiply(difference, sum_ab)
print(result)
print(time.time() - start_time)

[[138, 88, 68], [-154, -100, -78], [-14, -16, -12]]
0.0008919239044189453


## Part 4 - compare solutions with numpy.allclose()

In [25]:
print(np.allclose(result, numpy_result))

True
